/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/dialogs/alertDialog.vue')['default']
    Filter: typeof import('./src/components/utils/filter.vue')['default']
    InsertOrEditTask: typeof import('./src/components/dialogs/ToDoTask/insertOrEditTask.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sort: typeof import('./src/components/utils/sort.vue')['default']
    ToDoTaskCard: typeof import('./src/components/ToDoTaskCard.vue')['default']
    ToDoTaskPageHeader: typeof import('./src/components/page_headers/toDoTaskPageHeader.vue')['default']
  }
}
